# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('context', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('score_rating', models.CharField(blank=True, choices=[('1', '\u2606'), ('2', '\u2605'), ('3', '\u2605\u2606'), ('4', '\u2605\u2605'), ('5', '\u2605\u2605\u2606'), ('6', '\u2605\u2605\u2605'), ('7', '\u2605\u2605\u2605\u2606'), ('8', '\u2605\u2605\u2605\u2605'), ('9', '\u2605\u2605\u2605\u2605\u2606'), ('10', '\u2605\u2605\u2605\u2605\u2605')], max_length=5, null=True)),
                ('root_id', models.IntegerField(default=0)),
                ('reply_to', models.IntegerField(default=0)),
                ('reply_name', models.CharField(blank=True, max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
