# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171019_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score_rating',
            field=models.IntegerField(blank=True, choices=[('1', '\u2606'), ('2', '\u2605'), ('3', '\u2605\u2606'), ('4', '\u2605\u2605'), ('5', '\u2605\u2605\u2606'), ('6', '\u2605\u2605\u2605'), ('7', '\u2605\u2605\u2605\u2606'), ('8', '\u2605\u2605\u2605\u2605'), ('9', '\u2605\u2605\u2605\u2605\u2606'), ('10', '\u2605\u2605\u2605\u2605\u2605')], null=True),
        ),
    ]
